# PDFs Lesen

Zuerst importieren wir die Module die wir brauchen:

In [18]:
import camelot
import pandas as pd
import tabula

In [2]:
url = 'https://www.police.be.ch/police/de/index/ueber-uns/kantonspolizei/statistik/Verkehrsstatistik.assetref/dam/documents/POM/Police/de/Statistik/Bericht_110%20ohne%20AB_AS%20Gemeinden-Stand%202018%20%28D%29.pdf'

In [3]:
tables = camelot.read_pdf(url, pages='1')
tables

In [4]:
# <- Das funktioniert nicht so ganz. Wir ändern die flavor-Einstellung, lattice ist standard.

tables = camelot.read_pdf(url, flavor='lattice', pages = '1')
tables

In [5]:
# <- auch nicht. Wir ändern auf 'stream', dh camelot guckt nach Weissraum zwischen den Daten. 
tables = camelot.read_pdf(url, flavor='stream', pages = '1')
tables

In [6]:
# Tada! Das hat funktioniert. Aber er nimmt nur bis zu einer gewissen Zeilen. Deshalb definieren wir noch  
# die Fläche auf der sich die Tabelle befindet.
tables_stream = camelot.read_pdf(url, flavor='stream', pages = 'all', table_areas=['0,842,595,0'])
tables_stream[1].df

,0,1,2,3,4,5,6,7
0,,"Übersicht: Gemeinde ohne Autobahn, Autostrasse",,,,,,
1,2018,,,,,,,
2,Unfälle und Verunfallte,,,,,,,
3,nach Unfallfolgen und Gemeinde,,,,,,,
4,,,,,,davon,,
5,,,Unfälle mit,,,lebens-,,
6,,Unfälle mit,Personen-,,Schwer-,bedrohlich,erheblich,
7,,Sach-schaden,schaden,Getötete,verletzte,Verletzte¹,Verletzte¹,Leicht-verletzte
8,Total,2 489,2 397,34,506,30,476,2 344
9,Cormoret,3,6,0,1,0,1,8
10,Cortébert,2,0,0,0,0,0,0
11,Court,0,3,0,0,0,0,3
12,Courtelary,4,3,0,3,0,3,1
13,Crémines,2,3,0,1,0,1,2
14,Därligen,9,5,0,0,0,0,9
15,Därstetten,2,0,0,0,0,0,0
16,Deisswil bei Münchenbuchsee,1,0,0,0,0,0,0
17,Diemerswil,0,0,0,0,0,0,0
18,Diemtigen,4,4,0,2,0,2,6
19,Diessbach bei Büren,2,5,0,1,0,1,4
20,Dotzigen,6,3,0,1,0,1,4
21,Dürrenroth,2,1,0,0,0,0,1
22,Eggiwil,4,4,0,2,0,2,7
23,Epsach,1,1,0,1,0,1,0
24,Eriswil,0,2,0,1,0,1,1
25,Eriz,0,2,0,1,0,1,1
26,Erlach,1,0,0,0,0,0,0
27,Erlenbach im Simmental,9,9,0,1,0,1,10
28,Ersigen,5,1,0,0,0,0,2
29,Eschert,0,0,0,0,0,0,0
30,Evilard,3,3,0,1,0,1,2
31,Fahrni,0,1,0,1,0,1,0
32,Farnern,0,0,0,0,0,0,0
33,Ferenbalm,3,4,0,1,0,1,3
34,Finsterhennen,1,1,0,0,0,0,1
35,Forst-Längenbühl,0,0,0,0,0,0,0
36,Fraubrunnen,4,8,0,1,0,1,8
37,Frauenkappelen,1,1,0,0,0,0,1
38,Freimettigen,0,0,0,0,0,0,0
39,Frutigen,17,12,1,5,1,4,7
40,Gals,4,0,0,0,0,0,0
41,Gampelen,4,4,0,1,0,1,3
42,Gerzensee,1,2,0,0,0,0,2
43,Golaten,0,1,0,0,0,0,1
44,Gondiswil,0,1,0,1,0,1,0
45,Graben,1,1,0,0,0,0,1
46,Grandval,0,1,0,1,0,1,0
47,Grindelwald,7,5,0,1,0,1,4
48,Grossaffoltern,5,4,0,1,0,1,4
49,Grosshöchstetten,6,5,0,1,0,1,5
50,Gsteig,5,2,0,1,0,1,1
51,Gsteigwiler,1,0,0,0,0,0,0
52,Guggisberg,0,4,0,2,0,2,2
53,Gündlischwand,1,3,0,0,0,0,4
54,Gurbrü,1,2,0,0,0,0,2
55,Gurzelen,0,1,0,0,0,0,1
56,Guttannen,3,7,0,2,0,2,7
57,Habkern,0,2,0,1,1,0,1
58,Hagneck,2,1,0,0,0,0,1

## Datenbereinigung

In [12]:
#Wir schauen uns nun die Seite 3 an, um unsere Befehle für eine Standard-Seite anzupassen. 
# (da die erste Seite häufig etwas abweicht von den folgenden)

test_df = tables_stream[3].df # <- .df ist ein camelot-Befehl.
test_df.head(10)

,0,1,2,3,4,5,6,7
0,,"Übersicht: Gemeinde ohne Autobahn, Autostrasse",,,,,,
1,2018,,,,,,,
2,Unfälle und Verunfallte,,,,,,,
3,nach Unfallfolgen und Gemeinde,,,,,,,
4,,,,,,davon,,
5,,,Unfälle mit,,,lebens-,,
6,,Unfälle mit,Personen-,,Schwer-,bedrohlich,erheblich,
7,,Sach-schaden,schaden,Getötete,verletzte,Verletzte¹,Verletzte¹,Leicht-verletzte
8,Total,2 489,2 397,34,506,30,476,2 344
9,Langenthal,35,46,1,7,0,7,50

In [13]:
# <- soweit so cool, aber die Daten interessieren uns erst ab Zeile 9. Deshalb lesen wir die Tabelle erst ab da.
test_df[9:].head()

                      0   1   2  3  4  5  6   7
9            Langenthal  35  46  1  7  0  7  50
10  Langnau im Emmental  17  19  2  2  0  2  17
11              Lauenen   1   0  0  0  0  0   0
12               Laupen  12   5  0  0  0  0   6
13           Lauperswil   4  10  0  2  1  1  13

In [15]:
# diese Tabelle packen wir in eine Variable
data = test_df[9:]

data.columns = headers

In [19]:
# Jetzt kommt der Clou: wir erstellen eine For-Loop, welche die Daten jeder Seite zusammenklebt.  

ff = pd.DataFrame() # Leere liste, in die wir gleich die Seiten dazuholen. 

# Damit die Spalten wieder Überschriften haben, machen wir eine Liste mit neuen Spaltennamen
headers = ['Gemeinde', 'Sachschaden', 'Personenschaden', 'Getötete', 'Schwerverletzte', 
           'Lebensbedrohlich Verletzte' 'Erheblich Verletzte', 'Leichtverletzte']

for number in range(0, 8):
    temp = tables_stream[number].df
    temp = temp[9:]
    templcolumns = headers
    ff = pd.concat(ff, temp)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [ ]:
ff.info()

In [ ]:
def clean(elem):
    if elem == "":
        return 0
    else: return elem

ff = ff.applymap(clean)    # applymap ist eine Pandas-Funktion, die über die gesamte Tabelle geht.

In [ ]:
# Zwischenzeitlich die Gemeinden löschen, und am Schluss hier wieder anhängen. Unterdessen alle anderen Spalten
# zu Ints verwandeln.

gem = ff['Gemeinde']
del ff['Gemeinde']
ff = ff.astype(int)
ff['Gemeinde'] = gem
ff = ff[['Gemeinde', 'Sachschaden', 'Personenschaden', 'Getötete', 'Schwerverletzte', 
           'Lebensbedrohlich Verletzte' 'Erheblich Verletzte', 'Leichtverletzte']].copy #um die Reihenfolge

In [ ]:
#index anpassen
ff = ff.reset_index()
del ff['index']

In [ ]:
ff